Algoritmo "entradaExenso"

Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   leia(numero)
   escolha numero
   caso 1
      escreva("UM")
   caso 2
      escreva("DOIS")
   caso 3
      escreva("TRÊS")
   caso 4
      escreva("QUATRO")
   outrocaso
      escreva("Número invalido")
   fimescolha

Fimalgoritmo