Algoritmo "numerosPares"
// Disciplina  :  2019.2 - Projeto de Algoritmo
// Professor   : Diego Braga Galiza Viana
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2019
Var
   // Seção de Declarações das variáveis
   x:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para x de 2 ate 10 passo 2 faca
      escreva(x)
   fimpara

Fimalgoritmo