Algoritmo "testaPar"
// Disciplina  :  2019.2 - Projeto de Algoritmo 
// Professor   : Diego Braga Galiza Viana 

Var
   // Seção de Declarações das variáveis
   numero :inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite seu numero: ")
   leia(numero)
   
      se numero % 2 = 0 entao
         escreva("O número", numero, " é par")
      senao
           escreva("O número", numero, " impar")
      fimse

Fimalgoritmo